import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Blog website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <nav className={styles.NavBar}>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Contact Us</li>
          </ul>
        </nav>
        <div >
          <h1 className={styles.Main}>Ensure Blog</h1>
            <p>lorem-ipsum......... </p>
        </div>
      </body>

      <footer>
        Copywrite@Ensure-2023.
      </footer>
    </div>
  )
}
